#!/usr/bin/python3 -B

# Remonda Adrian 2016

import os
from elenv import env

comm = "ssh " + " -t " + env.user + "@" + env.ip + ' \"cd ' + env.default_remote_path + '; bash\"'
print(comm)

print ("## Trying to connect with: " + comm)
os.system(comm)





